version: "3.7"
services:
  mysqldb:
    build: ./database
    image: mysql_url:latest
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  mysqldb-test:
    build: ./database
    image: mysql_url:latest
    container_name: mysqldb-test
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
